---
title: "Assignment 3 - Towards the final project"
subtitle: "Bocconi University - 20236 Time Series Analysis \\linebreak Group 27 | Anna-Bella Dreyfus, Emanuele Artoni, Artūrs Jānis Ņikitins,
  Madelief van Weerdenburg"
output:
  pdf_document:
    latex_engine: xelatex
    fig_caption: true
    extra_dependencies:
        - float
        - subfig
fontsize: 10pt
geometry: margin=2cm
header-includes:
- \setlength{\textfloatsep}{6pt}
- \setlength{\intextsep}{6pt}
---

```{r setup, include=FALSE}
rm(list = ls())
library(tidyverse)
library(dlm)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.pos = "H", fig.align = "center", out.extra = "", fig.width = 5, fig.height = 3, out.width = "67%")

set_theme(theme_classic())
update_theme(plot.title = element_text(hjust = 0.5), strip.background = element_blank())
```

```{r Implementation}
df <- read.csv("gistemp.csv", skip = 1, na.strings = "***")
monthly_matrix <- as.matrix(df[, 2:13])
monthly_vector <- as.numeric(t(monthly_matrix))

gistemp_ts_raw <- ts(monthly_vector, start = c(1880, 1), frequency = 12)

# Eliminating seasonality
stl_decomp <- stl(gistemp_ts_raw, s.window = "periodic")
gistemp_ts <- gistemp_ts_raw - stl_decomp$time.series[,"seasonal"]

```

# Dynamic linear models

```{r rw and llt}
print(1)
```

# Parameter estimation

```{r params estimation}
# builder functions
build_rw <- function(params) {
  dlmModPoly(order = 1, dV = params[1], dW = params[2])
}
build_llt <- function(params) {
  dlmModPoly(order = 2, dV = params[1], dW = c(params[2], params[3]))
}
set.seed(88888)
start_rw <- c(1,1)
start_llt <- c(1,1,1)

# ML estimation - rw
mle_rw <- dlmMLE(gistemp_ts,
                  parm = start_rw,
                  build = build_rw,
                  hessian = TRUE
                  )
# output - rw
sigma2_rw <- mle_rw$par[1]
tau2_rw <- mle_rw$par[2]
se_rw <- sqrt(diag(solve(mle_rw$hessian)))

# - llt
mle_llt <- dlmMLE(gistemp_ts,
       parm = start_llt,
       build = build_llt,
       hessian = TRUE
       )

# output - llt
sigma2_llt <- mle_llt$par[1]
tau2_llt <- mle_llt$par[2]
gamma2_llt <- mle_llt$par[3]
se_llt <- sqrt(diag(solve(mle_llt$hessian)))

mle_table <- data.frame(
  Model     = c("RW", "RW", "LLT", "LLT", "LLT"),
  Parameter = c("sigma^2", "tau^2", "sigma^2", "tau^2", "gamma^2"),
  MLE       = c(sigma2_rw, tau2_rw, sigma2_llt, tau2_llt, gamma2_llt),
  SE        = c(se_rw, se_llt)
)
knitr::kable(mle_table, digits = 6, caption = "MLE estimates and asymptotic standard errors")
```

# Filtering and smoothing

```{r, fig.width=10, fig.height=7}
# note that the following are the fitted models:
mod_rw  <- build_rw(mle_rw$par)
mod_llt <- build_llt(mle_llt$par)

## RW - Filtering

filter_sd <- function(filt) {
  vars <- dlmSvd2var(filt$U.C, filt$D.C)
  sqrt(sapply(vars, function(v) v[1, 1]))
}

rw_Filt <- dlmFilter(gistemp_ts, mod_rw)
m_filt <- dropFirst(rw_Filt$m)
rw_filt_sd <- filter_sd(rw_Filt)[-1]


z95 <- qnorm(0.975)
ci_upper <- m_filt + z95 * rw_filt_sd
ci_lower <- m_filt - z95 * rw_filt_sd

t_vals <- time(m_filt)

plot(gistemp_ts, type = 'l', col = "grey60", ylab = "Anomaly (Celsius)", 
     xlab = "Year", main = "RW – Filtering", cex.main = 0.8)

polygon(c(t_vals, rev(t_vals)),
        c(ci_upper, rev(ci_lower)),
        col = adjustcolor("orange", alpha.f = 0.7),
        border = NA)

lines(gistemp_ts, col = "grey60", lwd = 1)

lines(m_filt, col = "seagreen", lwd = 1.5)


## RW - Smoothing

rw_Smooth <- dlmSmooth(gistemp_ts, mod_rw)

s_smooth <- dropFirst(rw_Smooth$s)
s_smooth <- as.numeric(s_smooth)

S_smooth <- dlmSvd2var(rw_Smooth$U.S, rw_Smooth$D.S)
S_smooth <- dropFirst(S_smooth)

smooth_sd <- sqrt(unlist(S_smooth))

ci_upper_smooth <- s_smooth + z95 * smooth_sd
ci_lower_smooth <- s_smooth - z95 * smooth_sd

t_vals <- time(gistemp_ts)[seq_along(s_smooth)]

plot(gistemp_ts, type = "l", col = "grey60", ylab = "Anomaly (Celsius)", 
     xlab = "Year", main = "RW – Smoothing", cex.main = 0.8)

polygon(c(t_vals, rev(t_vals)),
        c(ci_upper_smooth, rev(ci_lower_smooth)),
        col = adjustcolor("orange", alpha.f = 0.7),
        border = NA)

lines(gistemp_ts, col = "grey60", lwd = 1)

lines(t_vals, s_smooth, col = "brown", lwd = 1.5)


## LLT - Filtering

llt_Filt <- dlmFilter(gistemp_ts, mod_llt)
m_llt <- dropFirst(llt_Filt$m[, 1])
m_llt <- as.numeric(m_llt)
C_llt <- dlmSvd2var(llt_Filt$U.C, llt_Filt$D.C)
C_llt <- dropFirst(C_llt)

llt_filt_sd <- sqrt(sapply(C_llt, function(x) x[1, 1]))


ci_upper_llt <- m_llt + z95 * llt_filt_sd
ci_lower_llt <- m_llt - z95 * llt_filt_sd

t_vals <- time(gistemp_ts)[seq_along(m_llt)]

plot(gistemp_ts, type = "n", col = "grey60", ylab = "Anomaly (Celsius)",
     xlab = "Year", main = "LLT – Filtering", cex.main = 0.8)

polygon(c(t_vals, rev(t_vals)),
        c(ci_upper_llt, rev(ci_lower_llt)),
        col = adjustcolor("orange", alpha.f = 0.4),
        border = NA)

lines(gistemp_ts, col = "grey60", lwd = 1)

lines(t_vals, m_llt,
      col = "seagreen",
      lwd = 2)



## LLT - Smoothing

llt_Smooth <- dlmSmooth(gistemp_ts, mod_llt)
s_smooth_llt <- dropFirst(llt_Smooth$s[, 1])
s_smooth_llt <- as.numeric(s_smooth_llt)
S_smooth_llt <- dlmSvd2var(llt_Smooth$U.S, llt_Smooth$D.S)
S_smooth_llt <- dropFirst(S_smooth_llt)
smooth_sd_llt <- sqrt(sapply(S_smooth_llt, function(x) x[1, 1]))

ci_upper_llt <- s_smooth_llt + z95 * smooth_sd_llt
ci_lower_llt <- s_smooth_llt - z95 * smooth_sd_llt

plot(gistemp_ts, type = "l", col = "grey60", ylab = "Anomaly (Celsius)", 
     xlab = "Year", main = "LLT – Smoothing", cex.main = 0.8)

polygon(c(t_vals, rev(t_vals)),
        c(ci_upper_llt, rev(ci_lower_llt)),
        col = adjustcolor("orange", alpha.f = 0.7),
        border = NA)

lines(gistemp_ts, col = "grey60", lwd = 1)

lines(t_vals, s_smooth_llt, col = "brown", lwd = 1.5)


## interpretation:

#In both the random walk plus noise and local linear trend model it is visible that the credible
#interval band is tighter. In the graphs they are given by the orange hue around their respective
#green and brown (filtered and smoothed) estimates. The gray in the graphs plots the observed data. 
#The credible interval being tighter when smoothing rather than filtering is likely in part due
#to it being determined by more data. In filtering, at time t, one uses only data from time 1 
#through t, while in smoothing one takes the entire data set from 1 through T. Using 'future' 
#information, thus reduces uncertainty, which leads to a tighter credible interval. 

```

# Forecasting, model checking and model evaluation

```{r forecasting}

# Split dataset
max_date <- max(time(gistemp_ts))
training_date <- max_date - 20

gistemp_ts_train <- window(gistemp_ts, end = training_date)
gistemp_ts_test <- window(gistemp_ts, start = training_date + 1/frequency(gistemp_ts))

# Train models

set.seed(88888)

# Redo builders with log-variances

build_rw_train <- function(params) {
  dlmModPoly(order = 1, dV = exp(params[1]), dW = exp(params[2]))
}
build_llt_train <- function(params) {
  dlmModPoly(order = 2, dV = exp(params[1]), dW = c(exp(params[2]), exp(params[3])))
}

# ML estimation - rw
mle_rw_train <- dlmMLE(gistemp_ts_train,
                  parm = c(0, 0),
                  build = build_rw_train,
                  hessian = TRUE
                  )
# output - rw
sigma2_rw_train <- exp(mle_rw_train$par[1])
tau2_rw_train <- exp(mle_rw_train$par[2])

# - llt
mle_llt_train <- dlmMLE(gistemp_ts_train,
       parm = c(0, 0, 0),
       build = build_llt_train,
       hessian = TRUE
       )

# output - llt
sigma2_llt_train <- exp(mle_llt_train$par[1])
tau2_llt_train <- exp(mle_llt_train$par[2])
gamma2_llt_train <- exp(mle_llt_train$par[3])

mle_table_train <- data.frame(
  Model     = c("RW", "RW", "LLT", "LLT", "LLT"),
  Parameter = c("sigma^2", "tau^2", "sigma^2", "tau^2", "gamma^2"),
  MLE       = c(sigma2_rw_train, tau2_rw_train, sigma2_llt_train, tau2_llt_train, gamma2_llt_train)
)
knitr::kable(mle_table_train, digits = 6, caption = "MLE estimates (training sample)")

# filters & forecast errors

mod_rw_train  <- dlmFilter(gistemp_ts, build_rw_train(mle_rw_train$par))
mod_llt_train <- dlmFilter(gistemp_ts, build_llt_train(mle_llt_train$par))

gistemp_frcst_rw <- gistemp_ts_test - window(mod_rw_train$f, start = training_date + 1/frequency(gistemp_ts))
gistemp_frcst_rw_std <- window(residuals(mod_rw_train, sd = FALSE), start = training_date + 1/frequency(gistemp_ts))

gistemp_frcst_llt <- gistemp_ts_test - window(mod_llt_train$f, start = training_date + 1/frequency(gistemp_ts))
gistemp_frcst_llt_std <- window(residuals(mod_llt_train, sd = FALSE), start = training_date + 1/frequency(gistemp_ts))

# Model checking
acf(gistemp_frcst_rw_std)
acf(gistemp_frcst_llt_std)

qqnorm(gistemp_frcst_rw_std)
qqline(gistemp_frcst_rw_std)

qqnorm(gistemp_frcst_llt_std)
qqline(gistemp_frcst_llt_std)

# RMSE
rmse_rw <- sqrt(mean(gistemp_frcst_rw^2))
rmse_llt <- sqrt(mean(gistemp_frcst_llt^2))

rmse_table <- data.frame(
  Model = c("RW", "LLT"),
  RMSE = c(rmse_rw, rmse_llt)
)

knitr::kable(rmse_table, digits = 6, caption = "Test-set RMSE")

# Interpretation

# The ACFs of the standardized forecast errors show some residual autocorrelation,
# with a few lags exceeding the approximate confidence bounds.
# This suggests that neither model fully removes temporal dependence in the test-set forecast errors.

# The QQ plots are reasonably close to linear in the middle part, but deviate in the tails.
# Thus, the normality assumption is reasonable but imperfect, especially for more extreme errors.

# Both models have effectively the same test-set RMSE (LLT is negligibly smaller RW).
# Moreover, the variance for the estimated slope innovation is essentially zero,
# which suggests that the data do not support a time-varying slope component.
# Therefore, the LLT model does not provide a meaningful improvement over the more
# parsimonious RW model.

```

# Questions (Discussion)
