\documentclass[10pt]{article}

\usepackage{graphicx}
\usepackage[a4paper, margin=2cm]{geometry}
\usepackage{microtype}
\usepackage{lmodern}
\usepackage{fontspec}
\usepackage{parskip}
\usepackage{tabularray}

\usepackage{mathtools}
\usepackage{siunitx}
\usepackage{amsfonts}

\usepackage{hyperref}
\usepackage{float}
\usepackage{booktabs}
\usepackage{makecell}
\usepackage{threeparttable}

\title{Final project for Time Series Analysis (20236)}
\author{%
Group 27\\[0.5em]
\begin{tabular}{c}
Emanuele Artoni, Anna-Bella Dreyfus \\
Arturs Janis Nikitins, Madelief van Weerdenburg
\end{tabular}
}
\date{\today}

\begin{document}
\maketitle
% \pagebreak
\textbf{Scientific question.} We ask whether monthly Northern Hemisphere GISTEMP anomalies document global warming, and compare a discrete-regime HMM summary with continuous latent-trend DLMs.

\section{GISTEMP}

\subsection*{Data exploration}

The GISTEMP series contains monthly Northern Hemisphere temperature anomalies relative to the 1951-1980 reference period.
This is important to note because the observations are not raw temperatures, so any seasonal components capture residual month-specific structure in anomalies, not a usual winter-summer temperature cycle.

\begin{figure}[bht]
\setlength\abovecaptionskip{-10pt}
\centering
\includegraphics[width=1\linewidth]{Final_Project_Part_1_Rewritten_Group_27_files/figure-latex/fig-raw-series-1}
\caption{Monthly Northern Hemisphere temperature anomalies (grey) and their 10-year moving average (black).\label{fig:fig-raw-series}}
\end{figure}

Figure \ref{fig:fig-raw-series} shows a clear long-run increase in temperature anomalies.
The increase is moderate until the mid-20th century, flattens around 1940-1970, and becomes much steeper from the late 1970s onward.
The dispersion around the trend appears roughly stable, so an additive decomposition is more natural than a multiplicative one, especially because anomalies can be negative.

The STL decomposition in Figure \ref{fig:fig-stl-decomposition} confirms that the dominant component is the low-frequency trend.
The time-varying seasonal component is small relative to the trend: its range is only a fraction of the full increase in anomalies.
The residual component is centered around zero with a constant variance and no noticeable outliers.
For the modelling below, we remove this small residual seasonal component before fitting HMMs and the univariate RW/LLT DLMs, while also considering a seasonal DLM fitted directly to the raw monthly series.

\begin{figure}[htb]
\setlength\abovecaptionskip{-10pt}
\centering
\includegraphics[width=1\linewidth]{Final_Project_Part_1_Rewritten_Group_27_files/figure-latex/fig-stl-decomposition-1}
\caption{STL decomposition of monthly temperature anomalies.}
\label{fig:fig-stl-decomposition}
\end{figure}

\subsection*{Do the data document global warming?}

In both classes of state-space models models, the observed anomaly is interpreted as a noisy signal of an unobserved state process.
The difference is the nature of that state.
In a Hidden Markov Model (HMM), the state $S_t$ is discrete.
In a Dynamic Linear Model (DLM), the latent state is continuous and evolves through Gaussian innovations.

\subsubsection*{Hidden Markov Models}

For the main HMM specification, we use the seasonally adjusted series $Y_t$ and a Gaussian HMM with a state-dependent level:
\[
Y_t \mid S_t = j \sim N(\mu_j, \sigma_j^2).
\]
For each specification we repeat model fitting several times and retain the converged fit with the largest log-likelihood to account for local likelihood optima.
For model selection, we use likelihood criteria together with interpretability of the decoded paths.

\begin{figure}[htb]
\setlength\abovecaptionskip{-10pt}
\centering
\includegraphics[width=1\linewidth]{Final_Project_Part_1_Rewritten_Group_27_files/figure-latex/hmm-ic-plot-1}
\caption{Level-HMM fit measures by number of states.}
\label{fig:hmm-ic-plot}
\end{figure}

\begin{table}[!h]
\centering
\caption{\label{tab:hmm-param-table}\label{tbl:hmm-params}Selected 6-state level HMM parameters.}
\centering
\begin{threeparttable}
\begin{tabular}[t]{rlrrrl}
\toprule
State & Interpretation & Mean anomaly & State sd & Occupancy share & Expected duration\\
\midrule
1 & very low & -0.446 & 0.187 & 0.183 & 14.0\\
2 & low & -0.156 & 0.138 & 0.314 & 9.5\\
3 & middle & 0.139 & 0.150 & 0.263 & 12.8\\
4 & partly high & 0.448 & 0.110 & 0.057 & 7.7\\
5 & high & 0.774 & 0.173 & 0.107 & 33.6\\
6 & very high & 1.289 & 0.252 & 0.076 & \\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: }
\item States reordered by mean anomaly.
\item State 6 is absorbing; thus, the expected duration is infinite.
\end{tablenotes}
\end{threeparttable}
\end{table}

\begin{figure}[htb]
\setlength\abovecaptionskip{-10pt}
\centering
\includegraphics[width=1\linewidth]{Final_Project_Part_1_Rewritten_Group_27_files/figure-latex/hmm-decoded-plot-1}
\caption{Decoded states from the selected level HMM. Horizontal lines represent estimated state means.}
\label{fig:hmm-decoded-plot}
\end{figure}

The level HMM is useful as a discrete summary of the warming path.
The selected five-state model separates the series into increasingly warm anomaly regimes.
The choice of five states is mainly interpretive: likelihood-based criteria may favor larger or trend-based models, but the additional flexibility weakens the clean regime interpretation.
The decoded states in Figure \ref{fig:hmm-decoded-plot} mostly track the long-run increase in anomalies, which is informative but also exposes the limitation of the HMM approach as the later states discretize an increasing trend without additional interpretative value.

We also fitted a linear-trend HMM with emission model
\[
Y_t \mid S_t = j \sim N(\alpha_j + \beta_j t, \sigma_j^2).
\]
This specification is more flexible because each state has both a level and a slope.
However, the regimes become harder to interpret: states represent different fitted lines rather than clean regimes, i.e., the states do not represent ``heating'' or ``cooling'' trends as much as categorize observations by which lines they are near to.
For this reason, the level HMM is the clearer HMM benchmark, while the DLMs below should be more appropriate for a continuously evolving trend.

\subsubsection*{Dynamic Linear Models}

An HMM discretizes a gradual process, while DLMs model the latent temperature level as a continuous Gaussian state.
We first fit two models to the seasonally adjusted series:
\[
Y_t = \mu_t + \epsilon_t, \qquad \epsilon_t \sim N(0, \sigma^2),
\]
with either a random-walk state
\[
\mu_t = \mu_{t-1} + \eta_t, \qquad \eta_t \sim N(0, \tau^2),
\]
or a locally linear trend
\[
\mu_t = \mu_{t-1} + \beta_{t-1} + \eta_t, \qquad \eta_t \sim N(0, \tau^2),
\]
\[
\beta_t = \beta_{t-1} + \zeta_t, \qquad \zeta_t \sim N(0, \gamma^2).
\]
Finally, we fit a single structured DLM to the raw monthly series, adding a 12-period seasonal DLM:
\[
Y_t = \mu_t + s_t + \epsilon_t, \qquad s_t = - \sum_{j=1}^{11} s_{t-j} + \omega_t, \omega_t \sim N(0, \varsigma^2).
\]

\begin{table}[htbp]
\centering
\caption{\label{tab:dlm-param-table}\label{tbl:dlm-params}DLM maximum likelihood estimates and asymptotic standard errors.}
\centering
\begin{tabular}[t]{llrr}
\toprule
Model & Parameter & Estimate & S.E.\\
\midrule
RW & sigma2 & 0.020790 & 0.001122\\
RW & tau2 & 0.004940 & 0.000691\\
LLT & sigma2 & 0.020759 & 0.001122\\
LLT & tau2 & 0.004971 & 0.000696\\
LLT & gamma2 & 0.000000 & \\
\addlinespace
LLT + seasonal & sigma2 & 0.020259 & 0.001058\\
LLT + seasonal & tau2 & 0.004164 & 0.000580\\
LLT + seasonal & gamma2 & 0.000000 & \\
LLT + seasonal & seasonal var & 0.000007 & 0.000002\\
\bottomrule
\multicolumn{4}{l}{Note: Variance parameters are on the original scale; blank S.E.}\\
\multicolumn{4}{l}{entries are omitted for parameters estimated at the}\\
\multicolumn{4}{l}{numerical lower bound.}\\
\end{tabular}
\end{table}

\begin{table}[!h]
\centering
\caption{\label{tab:dlm-fit-table}\label{tbl:dlm-fit}DLM fit summary.}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{lrrr}
\toprule
Model & Log-likelihood & AIC & BIC\\
\midrule
RW & 2084.60 & -4165.21 & -4154.27\\
LLT & 2070.34 & -4134.68 & -4118.28\\
LLT + seasonal & 1939.46 & -3870.92 & -3849.05\\
\bottomrule
\multicolumn{4}{l}{\textsuperscript{a} RW and LLT are fit on the seasonally adjusted series}\\
\multicolumn{4}{l}{and thus are comparable; the LLT plus seasonal is}\\
\multicolumn{4}{l}{fitted to the raw monthly series, so it's likelihood}\\
\multicolumn{4}{l}{is not comparable.}\\
\end{tabular}
\end{table}

\begin{figure}[htb]
\setlength\abovecaptionskip{-10pt}
\centering
\includegraphics[width=1\linewidth]{Final_Project_Part_1_Rewritten_Group_27_files/figure-latex/dlm-smoothing-plots-1}
\caption{Smoothed latent temperature level with 95\% pointwise intervals.}
\label{fig:dlm-smoothing-plots}
\end{figure}

The DLMs directly estimate the latent warming trend.
Figure \ref{fig:dlm-smoothing-plots} shows that all three specifications recover the same qualitative pattern: a relatively flat mid-century period followed by a sustained recent increase.
On the seasonally adjusted series, Table \ref{tbl:dlm-fit} favors the RW model over the LLT by likelihood, AIC and BIC; the LLT slope innovation variance is estimated at the lower bound, so the additional stochastic slope-state flexibility is not supported by the data.
The LLT plus seasonal model remains useful as a full-series specification because the trend and seasonal states are estimated jointly from the raw observations, rather than treating STL components as separately observed time series.
The robust conclusion is sustained recent warming, not a precisely identified stochastic acceleration process.

\begin{table}[!h]
\centering
\caption{\label{tab:forecast-tables}\label{tbl:forecast-sa}One-step-ahead forecast diagnostics on the final 20 years.}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
Model & RMSE & MAE & ACF(1) & ACF(2) & Approx. 95\% coverage\\
\midrule
RW & 0.186 & 0.144 & 0.262 & 0.071 & 0.942\\
LLT & 0.185 & 0.144 & 0.261 & 0.070 & 0.942\\
LLT + seasonal & 0.172 & 0.132 & 0.234 & 0.052 & 0.958\\
\bottomrule
\multicolumn{6}{l}{\textsuperscript{a} Seasonal adjustment for RW and LTT is estimated from the training sample}\\
\multicolumn{6}{l}{only.}\\
\end{tabular}
\end{table}

\begin{figure}[htb]
\setlength\abovecaptionskip{-10pt}
\centering
\includegraphics[width=1\linewidth]{Final_Project_Part_1_Rewritten_Group_27_files/figure-latex/forecast-diagnostic-plot-1}
\caption{Forecast-error diagnostics for the LLT plus seasonal DLM: standardized one-step-ahead errors on the final 20 years.}
\label{fig:forecast-diagnostic-plot}
\end{figure}

The forecast diagnostics are deliberately light: their role is to check whether the fitted state-space models leave obvious structure in one-step-ahead errors.
The RW/LLT comparison is made on a seasonally adjusted series constructed without using the test period; the structured DLM is checked directly on the raw series.
Figure \ref{fig:forecast-diagnostic-plot} suggests acceptable marginal calibration, but the positive lag-1 autocorrelation shows that some short-run dependence remains.
This does not affect the long-run warming conclusion, but it means the model is not a complete description of monthly short-run dynamics.

\subsubsection*{Conclusion}

The GISTEMP data document global warming in the sense relevant for this project: the latent long-run anomaly trend is increasing, and the increase is especially visible in the recent part of the sample.
The HMM analysis gives a useful discrete summary of the data path, but the decoded states mostly track the upward trend and their regime interpretation is partly artificial.
The DLM analysis is more directly suited to the research question because it estimates a continuous latent temperature level, while the near-zero slope innovation variance warns against overclaiming a separately identified stochastic acceleration process.
The seasonal effects are small relative to the trend, so the modelling implication is clear: the central feature of the data is not seasonality, but a persistent low-frequency increase in temperature anomalies, with a markedly steeper recent trend.

\pagebreak
\section{GHCN}
In the second part of the report, we turn to temperature prediction using Global Historical Climatology Network (GHCN) data on weather-station-recorded maximum daily temperatures and Dynamic Linear Models (DLMs).
The question of importance is to what extent spatial correlation is informative for weather prediction.

\subsection*{Data}

We use GHCN data on the \textit{PASO ROBLES MUNI AP} (Paso Robles), \textit{SAN FRANCISCO DWTN} (San Francisco) and \textit{BAKER CITY AP} (Baker City) stations.
The three stations were selected to have both a nearby pair and a distant comparison station.
San Francisco and Paso Robles are separated by about \SI{283}{km}, while Baker City is much farther away, at about \SI{875}{km} and \SI{1046}{km}, respectively.
This gives enough spatial variation to test whether a distance-based covariance structure captures stronger latent dependence for nearby stations and weaker dependence for distant stations.

From the GHCN dataset, we select daily maximum temperatures recorded at each station from 1948-07-01 to 2024-12-31.
We transform the recorded temperatures into Celsius.
To ease seasonality adjustments, we omit observations for Feb 29.
We subset the sample into a DLM estimation sample from 1948-07-01 to 2014-12-31 and a prediction evaluation sample from 2015-01-01 to 2024-12-31.
Baker City has 30 missing observations for Sep 2001; however, this is unlikely to materially affect our results as the Kalman filter is robust to missing observations and the missing block is outside our evaluation window.
In the end, for each station we have \num{24274} daily observations for the training sample and \num{3650} observations for the evaluation sample.

We deseasonalize the series at the station level by subtracting from each observation the average value for the corresponding day of the year in the training sample.
Before subtracting the seasonal effects, the day-of-the-year averages are circularly smoothed with a 31-day moving average and demeaned.

The seasonal effects and deseasonalized series are shown in Figure~\ref{fig:data}.
As expected, summer months display higher average maximum temperatures than winter months.
Paso Robles and Baker City exhibit greater seasonal variability (maximum temperatures are up to \SI{10}{}--\SI{15}{\celsius} lower in winter days and \SI{10}{}--\SI{15}{\celsius} higher in summer days than on average), while maximum temperatures in San Francisco vary only by \SI{5}{\celsius} from the average.
After deseasonalization, Paso Robles has the warmest weather -- maximum temperatures vary between \SI{10}{} and \SI{40}{\celsius} with an average of around \SI{25}{\celsius}.
San Francisco has an average maximum daily temperature of \SI{18}{\celsius}; most days have a maximum temperatures between \SI{10}{} and \SI{20}{\celsius} degrees, with a fatter tail surpassing \SI{30}{\celsius}.
Baker City has the coldest but most varied weather: average maximum daily temperatures are \SI{15}{\celsius}, ranging from freezing temperatures to approaching \SI{30}{\celsius}.

Overall, the deseasonalized temperatures do not display any strong trends; thus, random-walk plus noise models could be considered suitable for modelling this data.

\begin{figure}[htbp]
\centering
\setlength\abovecaptionskip{-10pt}
\includegraphics[width=1\linewidth,]{Final_Project_Part_2_Group_27_files/figure-latex/plot_data-1}
\caption{Left: Day-of-year seasonal temperature effects. Right: Deseasonalized series (black) and 365-day rolling mean (red).}
\label{fig:data}
\end{figure}

\subsection*{Models and estimation}

We compare four DLM specifications: three random walk plus noise models, with independent, free, and spatially-constrained state evolution dependence, and a random walk with a seasonal component and spatially-correlated state innovations.

Let \(Y_t = (Y_{1t},Y_{2t},Y_{3t})'\) denote the vector of seasonality-adjusted daily maximum temperatures at the selected stations.
The latent state \(\theta_t=(\theta_{1t}, \theta_{2t},\theta_{3t})'\) represents the underlying local temperature level at each station.

The base random walk plus noise structure is
\[
\begin{aligned}
Y_t &= \theta_t + v_t,
& v_t &\sim \mathcal{N}_3(0,V), \\
\theta_t &= \theta_{t-1} + w_t,
& w_t &\sim \mathcal{N}_3(0,W),
\end{aligned}
\]
where, in all models, the observation error covariance matrix is diagonal:
\[
V = \operatorname{diag}(\sigma^2_{v,1},\sigma^2_{v,2},\sigma^2_{v,3}).
\]

\subsubsection*{1: Independent random walk plus noise (Independent)}

This model assumes that both observation errors and latent temperature innovations are independent across stations; thus, the state innovation covariance matrix is diagonal:
\[
W = \operatorname{diag}(\sigma^2_{w,1},\sigma^2_{w,2},\sigma^2_{w,3}).
\]

\subsubsection*{2: Random walk with unrestricted error covariance (Full W)}

This model allows the latent temperature levels of different stations to move together, but the dependence is estimated freely.
The state innovation covariance matrix is unrestricted positive definite:
\[
W =
\begin{pmatrix}
\sigma^2_{w,11} & \sigma_{w,12} & \sigma_{w,13} \\
\sigma_{w,21} & \sigma^2_{w,22} & \sigma_{w,23} \\
\sigma_{w,31} & \sigma_{w,32} & \sigma^2_{w,33}
\end{pmatrix}.
\]

\subsubsection*{3: Spatial random walk with distance-based covariance (Distance)}

This model imposes the assumption that nearby stations should have more strongly correlated latent temperature innovations than distant stations.
The state innovation covariance matrix is spatially structured:
\[
W_{jk}
=
\operatorname{Cov}(w_{j,t},w_{k,t})
=
\sigma_w^2 \exp(-\phi d_{jk}),
\qquad j,k=1,2,3,
\]
where \(d_{jk}\) is the great-circle distance between stations \(j\) and \(k\) measured in hundreds of km,
\(\sigma_w^2>0\) is the marginal innovation variance, and \(\phi>0\) controls
the rate at which dependence decays with distance.

Equivalently,
\[
W
=
\sigma_w^2
\begin{pmatrix}
1 & \exp(-\phi d_{12}) & \exp(-\phi d_{13}) \\
\exp(-\phi d_{21}) & 1 & \exp(-\phi d_{23}) \\
\exp(-\phi d_{31}) & \exp(-\phi d_{32}) & 1
\end{pmatrix}.
\]


\subsubsection*{4: Spatial random walk with seasonal component (Seasonal distance)}

For the seasonal model, the original non-seasonally-adjusted maximum temperatures are used.
Define the state vector as
\[
\theta_t =
\begin{pmatrix}
\mu_t & \gamma_t & \gamma_t^*
\end{pmatrix}'
=
\begin{pmatrix}
\mu_{1t}, \mu_{2t}, \mu_{3t}, \gamma_{1t}, \gamma_{2t}, \gamma_{3t}, \gamma^*_{1t}, \gamma^*_{2t}, \gamma^*_{3t}
\end{pmatrix}',
\]
where \(\mu_t\) is the vector of latent temperature levels and
\((\gamma_t,\gamma_t^*)\) is a first-order Fourier seasonal component.

The model is
\[
\begin{aligned}
Y_t &= F\theta_t + v_t,
& v_t &\sim \mathcal{N}_3(0,V), \\
\theta_t &= G\theta_{t-1} + w_t,
& w_t &\sim \mathcal{N}_{9}(0,W),
\end{aligned}
\]
with observation, transition and state covariance matrices
\[
F =
\begin{pmatrix}
I_3 & I_3 & 0_3
\end{pmatrix},
\qquad
G =
\begin{pmatrix}
I_3 & 0 & 0 \\
0 & \cos(\omega) I_3 & \sin(\omega) I_3 \\
0 & -\sin(\omega) I_3 & \cos(\omega) I_3
\end{pmatrix},
\qquad
\omega = \frac{2\pi}{365},
\qquad
W =
\begin{pmatrix}
W_\mu & 0 \\
0 & \sigma_s^2 I_{6}
\end{pmatrix},
\]
where the level innovation covariance \(W_\mu\) has a spatial structure as in Model 3, and \(\sigma_s^2>0\) controls the variability of the seasonal component.

\subsubsection*{Estimation}

The unknown parameters were estimated by maximum likelihood on the training sample.
Variance and distance penalty parameters were constrained to be positive through log parametrization, while the unrestricted error covariance matrix was parametrized via Cholesky factorization.
Initial variances and Cholesky parameters were set to unity, while, to ensure proper convergence, the distance penalty was re-estimated with initial values \(e^{-5}, e^{-8}, e^{-2}\), keeping the model with the largest likelihood.
Standard errors were computed from the inverse Hessian and transformed to the reported scale using the delta method.

Estimated parameters are reported in Table~\ref{tbl:params}.
To aid interpretability, we report estimated correlations and additionally the half-correlation distance for distance-based-covariance models.

The estimated level correlations are positive for all station pairs, suggesting that the three stations do not evolve independently.
In the Full W model, the strongest latent dependence is between Paso Robles and San Francisco, while Baker City has weaker correlations with the California stations.
This is consistent with the geography of the selected stations.
The distance model imposes a more parsimonious spatial structure with an estimated half-correlation distance of about \SI{395}{km}, implying that latent level shocks remain strongly correlated for nearby stations but decay with distance.
The seasonal distance model estimates the seasonal innovation variance at effectively zero, giving a similar fit to the distance model based on deseasonalized data.
Therefore, in this application, explicit stochastic seasonality adds little to a fixed annual harmonic.

Some variance estimates are on or close to the boundary of the parameter space, most notably the Paso Robles observation variance in the Independent model and the seasonal innovation variance in the Seasonal distance model.
These estimates should therefore be interpreted as approximately zero.

\begin{table}[htbp]
\centerline{
\begin{talltblr}[         %% tabularray outer open
caption={Estimated model parameters.\label{tbl:params}},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]Q[]Q[]Q[]Q[]},
hline{2}={9}{solid, black, 0.03em},
hline{2}={2,4,6,8}{solid, black, 0.03em, l=-0.5},
hline{2}={3,5,7}{solid, black, 0.03em, r=-0.5},
hline{3}={1-9}{solid, black, 0.05em},
hline{16}={1-9}{solid, black, 0.05em},
hline{1}={1-9}{solid, black, 0.08em},
hline{19}={1-9}{solid, black, 0.08em},
column{3,5,7,9}={}{halign=c},
cell{1}{1}={}{halign=c},
cell{1}{2}={c=2}{halign=c},
cell{1}{4}={c=2}{halign=c},
cell{1}{6}={c=2}{halign=c},
cell{1}{8}={c=2}{halign=c},
cell{2-18}{1}={}{halign=l},
cell{2-18}{2}={}{halign=c},
cell{2-18}{4}={}{halign=c},
cell{2-18}{6}={}{halign=c},
cell{2-18}{8}={}{halign=c},
}                     %% tabularray inner close
& Independent &  & Full W &  & Distance &  & Seasonal distance &  \\
& Est. & S.E. & Est. & S.E. & Est. & S.E. & Est. & S.E. \\
Obs. var.: Baker City & \num{1.484} & \num{0.119} & \num{2.684} & \num{0.122} & \num{3.460} & \num{0.092} & \num{3.440} & \num{0.092} \\
Obs. var.: Paso Robles & \num{0.000} & \num{0.001} & \num{1.864} & \num{0.093} & \num{2.432} & \num{0.071} & \num{2.424} & \num{0.071} \\
Obs. var.: San Francisco & \num{2.268} & \num{0.092} & \num{3.895} & \num{0.099} & \num{1.768} & \num{0.059} & \num{1.754} & \num{0.059} \\
Level var.: Baker City & \num{11.004} & \num{0.234} & \num{9.030} & \num{0.198} &  &  &  &  \\
Level var.: Paso Robles & \num{11.656} & \num{0.106} & \num{8.488} & \num{0.152} &  &  &  &  \\
Level var.: San Francisco & \num{5.302} & \num{0.144} & \num{3.426} & \num{0.093} &  &  &  &  \\
Level corr.: Baker City - Paso Robles &  &  & \num{0.355} & \num{0.010} & \num{0.160} & \num{0.007} & \num{0.158} & \num{0.007} \\
Level corr.: Baker City - San Francisco &  &  & \num{0.133} & \num{0.011} & \num{0.216} & \num{0.008} & \num{0.214} & \num{0.008} \\
Level corr.: Paso Robles - San Francisco &  &  & \num{0.750} & \num{0.010} & \num{0.609} & \num{0.007} & \num{0.607} & \num{0.007} \\
Common level var. &  &  &  &  & \num{7.270} & \num{0.090} & \num{7.300} & \num{0.090} \\
Distance penalty &  &  &  &  & \num{0.175} & \num{0.004} & \num{0.176} & \num{0.004} \\
Distance for 0.5 corr. &  &  &  &  & \num{395.538} & \num{9.386} & \num{393.441} & \num{9.305} \\
Seasonal var. &  &  &  &  &  &  & \num{0.000} &  \\
Num.Param. & \num{6} &  & \num{9} &  & \num{5} &  & \num{6} &  \\
Neg.Log.Lik. & \num{125093} &  & \num{121973} &  & \num{123234} &  & \num{123313} &  \\
AIC & \num{250199} &  & \num{243965} &  & \num{246477} &  & \num{246638} &  \\
\end{talltblr}
}
\end{table}

\subsection*{Forecast evaluation and diagnostics}

We evaluate the fitted models using one-step-ahead forecasts on the 2015--2024 evaluation sample.
Predictive accuracy is summarized using the mean forecast error, mean absolute error (MAE), root mean squared forecast error (RMSFE), empirical \SI{95}{\percent} predictive interval coverage, and the joint negative log predictive density (NLPD), which is the average negative log multivariate one-step-ahead predictive density from the Kalman filter, \(-\frac{1}{T}\sum_{t=1}^T \log p(y_t\mid y_{1:t-1})\).
Lower MAE, RMSFE and NLPD indicate better predictive performance, while coverage should be close to \SI{95}{\percent}.

\begin{table}[htbp]
\centering
\caption{Average model forecast performance.}
\label{tbl:perf_avg}
\begin{tabular}{lrrrrrr}
\toprule
Model & Mean & MAE & RMSFE & Coverage & Joint NLPD & \makecell{Avg. absolute\\whitened corr.} \\
\midrule
Independent & 0.002 & 2.499 & 3.330 & 0.946 & 7.853 & 0.214 \\
Full W & 0.002 & 2.520 & 3.327 & 0.946 & 7.743 & 0.062 \\
Distance & 0.002 & 2.508 & 3.326 & 0.947 & 7.794 & 0.143 \\
Seasonal distance & 0.002 & 2.505 & 3.326 & 0.947 & 7.795 & 0.143 \\
\bottomrule
\end{tabular}
\end{table}

Table~\ref{tbl:perf_avg} shows that all models are effectively unbiased and have empirical coverage close to the nominal \SI{95}{\percent} level.
Differences in point forecast accuracy are small: the Distance and Seasonal distance models have the lowest average RMSFE, but the gain over the Independent model is negligible.
Thus, spatial dependence does not materially improve marginal point forecasts.

The main gain from dependence appears instead in the joint predictive distribution.
The Full W model has the lowest joint NLPD, followed by the Distance model.
This means that allowing latent innovations to co-move improves the joint probabilistic fit, even though the average one-step-ahead point forecast errors remain very similar across models.
The unrestricted covariance model also has the lowest AIC and negative log-likelihood in Table~\ref{tbl:params}, so by likelihood-based criteria it is the best empirical specification.

Table~\ref{tbl:perf_avg} also gives a diagnostic for the value of modelling spatial dependence in the form of average absolute correlations of whitened forecast errors \(z_t = Q_t^{-1/2}(y_t - f_t)\).
The Independent model leaves substantial residual correlation, while the Full W model reduces the average absolute residual correlation from 0.214 to 0.062.
This suggests that the unrestricted state innovation covariance captures most of the contemporaneous dependence between stations.
The Distance and Seasonal distance models improve on independence but leave more residual cross-correlation than Full W.
This is the expected trade-off: the distance model is more interpretable and parsimonious, but the restriction that all correlations are determined by a single distance decay parameter is too rigid for these three stations.

Figure~\ref{fig:qq} shows that the Gaussian assumption is only approximate.
The central parts of the standardized forecast errors are close to normal, but the tails deviate visibly, especially for San Francisco and Paso Robles.
This indicates that the models understate the frequency of extreme temperature deviations, an issue not solved by allowing for cross-station dependence.

\begin{figure}[htbp]
\centering
\setlength\abovecaptionskip{-10pt}
\includegraphics[width=1\linewidth]{Final_Project_Part_2_Group_27_files/figure-latex/plot_eval_qq_comp-1}
\caption{Quantile-quantile plots of standardized one-step-ahead forecast errors for the Independent and Full W models.}
\label{fig:qq}
\end{figure}

Figure~\ref{fig:acf} shows remaining short-lag autocorrelation in the standardized forecast errors.
In most cases, the first few autocorrelations are negative, meaning that the random-walk plus noise structure slightly over-adjusts after large daily shocks.
The Full W model improves the cross-sectional dependence structure but does not remove this short-run serial dependence.
A richer temporal model, such as an autoregressive disturbance component or a local linear trend with more structured short-run dynamics, could address this, but it would go beyond the scope of this report.

\begin{figure}[htbp]
\centering
\setlength\abovecaptionskip{-10pt}
\includegraphics[width=1\linewidth]{Final_Project_Part_2_Group_27_files/figure-latex/plot_eval_acf_comp-1}
\caption{Estimated autocorrelation functions of standardized one-step-ahead forecast errors for the Independent and Full W models.}
\label{fig:acf}
\end{figure}

\subsection*{Conclusion}

The results show that spatial dependence is informative, but mainly for joint probabilistic modelling rather than for practical point prediction.
Average MAE and RMSFE are very similar across all four specifications: the best average RMSFE is 3.326 versus 3.330 for the independent model, a reduction of only about 0.1\%.
For the multivariate forecast distribution, the Full W model has the best likelihood-based fit, the lowest joint NLPD, and the smallest residual cross-station correlations.
The Full W model is therefore the best empirical model among those considered.

Its drawback is that the covariance structure is estimated freely and does not directly use geographic information.
The Distance model is less flexible but more interpretable: it is built on the assumption that nearby stations should have more strongly correlated latent temperature innovations, and it performs almost as well in RMSFE terms.
The Seasonal distance model adds little relative to deterministic deseasonalization, since the estimated seasonal innovation variance is effectively zero and its forecast performance is almost identical to the Distance model.

Overall, the evidence supports modelling cross-station dependence, but with limited gains for point prediction.

\end{document}
