---
title: "Bocconi University - 20236 Time Series Analysis"
subtitle: "**Group 27 | Anna-Bella Dreyfus, Emanuele Artoni, Artūrs Jānis Ņikitins, Madelief van Weerdenburg**"
output:
  pdf_document:
    latex_engine: xelatex
    fig_caption: yes
    extra_dependencies: ["float"]
fontsize: 10pt
geometry: margin=2cm
header-includes:
  - \setlength{\textfloatsep}{6pt}
  - \setlength{\intextsep}{6pt}
---

```{r setup, include=FALSE}
rm(list = ls())
library(forecast)
library(tidyverse)
library(gridExtra)
library(knitr)
library(depmixS4)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.align = "center", fig.pos = "H", out.extra = "")

set_theme(theme_classic())
update_theme(plot.title = element_text(hjust = 0.5), strip.background = element_blank())

plot_ts_gg <- function(
    x,
    title = NULL,
    xlab = NULL,
    ylab = NULL,
    aes = NULL,
    facet_ncol = 1,
    wrap_width = 45
) {
  if (!inherits(x, "ts")) {
    stop("Input must be ts.")
  }

  df <- tibble(
    Time = as.numeric(time(x)),
    Value = as.numeric(x)
  )

  p <- ggplot(df, aes(Time, Value, !!!aes)) +
    geom_line() +
    labs(title = title, x = NULL, y = ylab)

  p
}
```

## Task (a)

```{r, fig.height=3, fig.width=6, fig.show = "hold", out.width = "60%", fig.cap = "\\label{fig:main}nominal and real interest rates for 10Y Italian bonds"}
df <- read.csv("data_assHMM.csv", header = TRUE, sep = ",")

nom_bond <- as.ts(df$ITAbond_nom)
real_bond <- as.ts(df$ITAbond_real)

Time_useful <- as.Date(df$Time, format = "%Y_%m_%d")

obj1_nom <- tibble(
  Time = Time_useful,
  Value = nom_bond
)
obj2_real <- tibble(
  Time = Time_useful,
  Value = real_bond
)

ggplot(obj1_nom, aes(x = Time, y = Value, color = "Nominal rate"))+
  geom_line()+
  labs(title = NULL, x= NULL, y= "interest rates for Italian 10Y bonds")+
  geom_line(data = obj2_real, aes(x = Time, y = Value, color = "Real rate"))+
  theme(legend.position = "inside", legend.position.inside = c(0.3, 0.9)) +
  labs(color = NULL)


```
We have plotted the nominal and real interest rate for Italian 10Y bonds.
Why is using a HMM model reasonable?


